package 
{
    import flash.geom.*;

    public class defines extends Object
    {
        public static const SAVEGAME_VERSION_NR:int = 2;
        public static const START_SECTOR:int = 7;
        public static const PROTOKOLL_RESOURCE_ASSERT:Boolean = false;
        public static const DIR8_WEST:int = 7;
        public static const UNUSED_PLAYER_ID:int = 2147483647;
        public static var KEEP_ALIVE_INTERVAL:int;
        public static const DIR8_SOUTH_WEST_BIT:int = 1 << 2;
        public static const GUILDHOUSE_NAME_string:String = "guild_building";
        public static const SCROLL_RIGHT:int = 4;
        public static const PROTOKOLL_RESOURCE_CREATION_SIMPLE:Boolean = false;
        public static const PROTOKOLL_RESOURCE_CREATION:Boolean = false;
        public static const RECTANGLE_MAP_SIZE:int = 1122;
        public static const DIR8_NORTH_WEST:int = 3;
        public static const DEPOSITFOUND_NAME_string:String = "MineFound";
        public static const GARRISON_NAME_string:String = "Garrison";
        public static const SETTLER_BUILDER_string:String = "Carrier";
        public static const STREET_MAP_SIZE_FINAL:int = 8704;
        public static const FILENAME_QUEST_SETTINGS:String = "quest_settings.xml";
        public static const MAP_SCROLL_ACTIVATE_DELTA:Number = 1;
        public static const LOGISTICS_NAME_string:String = "Logistics";
        public static var TIME_OFFSET:int = 0;
        public static const SECTORS_X:int = 3;
        public static const SECTORS_Y:int = 3;
        public static const SCROLL_NOT:int = 0;
        public static const NEIGHBOUR_NORTH_WEST:int = 128;
        public static const DEPOSIT_HIDDEN_string:String = "DepositHidden";
        public static const NEIGHBOUR_NORTH:int = 1;
        public static const PROTOKOLL_RESOURCE_CREATION_DESTTIME:Boolean = false;
        public static const DIR8_SOUTH_WEST:int = 2;
        public static const PROTOKOLL_RESOURCE_CREATION_WRITE_TO_ARRAY:Boolean = false;
        public static var BIG_BROTHER_URL:String;
        public static const PRODUCTION_STOP_WAITTIME:int = 2500;
        public static const SCROLL_LEFT:int = 3;
        public static const LOAD_SECTOR_MODE_EDITOR_MODE:int = 1;
        public static const SECTOR_TYP_OPEN:int = 0;
        public static const BORDER_OFFSET_X:int = 50;
        public static const BORDER_OFFSET_Y:int = 50;
        public static const USER_DATA_STREET_BORDER_LEFT:int = 1;
        public static const MAX_PRODUCTION_AMOUNT:int = 25;
        public static const MAX_TRADE_LIMIT:int = 400;
        public static const SECTOR_TYP_CLOSED:int = 1;
        public static var STATIC_FILES_URL_LIST:Array;
        public static const DIR8_EAST:int = 5;
        public static const FILENAME_GAME_DEBUG_SETTINGS:String = "game_settings_debug.xml";
        public static const EXTENDED_BUILDING_SELECTION:Boolean = true;
        public static const STREAMING_SET_SCREEN_TO_BLACK_UNTIL_BACKGROUND_IS_STREAMED:Boolean = true;
        public static const STREET_MAP_WIDTH_2_FINAL:int = 128;
        public static const DIR8_NORTH_EAST:int = 0;
        public static const FILENAME_SHOP_CONFIG:String = "shopconfig.xml";
        public static const INT_SCALE_FACTOR:int = 10000;
        public static const DIR8_MAX:int = 8;
        public static const RECTANGLE_MAP_HEIGHT:int = 33;
        public static const UPDATE_REFRESH_COMMAND_MS:int = 7500;
        public static const SETTLER_DEFAULT_WORKER_string:String = "Carrier_";
        public static const MAX_DOUBLE_VALUE:Number = 1.79769e+308;
        public static const USE_PHP:Boolean = true;
        public static const PROTOKOLL_RESOURCE_CREATION_PATHFINDING:Boolean = false;
        public static var KEEP_ALIVE_URL:String;
        public static const GUI_RIGHT_BORDER:uint = 8;
        public static const MIN_UPGRADE_TIME_TO_MOVE_UPGRADING_BUILDING_FOR_GUI:int = 60000;
        public static const WINDOW_SIZE_MIN_HEIGHT:int = 576;
        public static const WAREHOUSES_NAME_string:String = "Warehouse";
        public static const MINEDEPOSITDEPLETED_NAME_string:String = "MineDepleted";
        public static const MAYORHOUSE_NAME_string:String = "Mayorhouse";
        public static const NEIGHBOUR_NORTH_EAST:int = 2;
        public static const DIR4_NORTH_WEST:int = 3;
        public static const DIR8_SOUTH_EAST:int = 1;
        public static const SAVEGAME_VERSION_NR_MAP_WITH_128:int = 1;
        public static const MINEDEPOSITDEPLETEDWATER_NAME_string:String = "MineDepletedDepositWater";
        public static const LOAD_SECTOR_MODE_DO_NOT_SET_GAME_RELEVANT_DATA:int = 2;
        public static const GAMETICK_SYSTEM_POSTPROCESS_TIME_MIN:Number = 2500;
        public static const NO_PLAYERID:int = -32767;
        public static const HARD_CURRENCY_RESOURCE_NAME_string:String = "HardCurrency";
        public static const STREET_MAP_WIDTH_FINAL_AND:int = 63;
        public static const ADVENTUREZONEID:int = -100;
        public static const DIR8_WEST_BIT:int = 1 << 7;
        public static const NEIGHBOUR_SOUTH_WEST:int = 32;
        public static var SUPPORT_URL:String;
        public static var GAMEWORLD:String = "";
        public static const WAREHOUSE_FULL_WAIT_TIME:int = 50000;
        public static const NEIGHBOUR_WEST:int = 64;
        public static const WINDOW_SIZE_MIN_WIDTH:int = 968;
        public static const USER_DATA_STREET_BORDER_RIGHT:int = 2;
        public static const STREET_MAP_WIDTH_FINAL:int = 64;
        public static const ANIMATE_FRAME_RATE:int = 15;
        public static const NEIGHBOUR_SOUTH_EAST:int = 8;
        public static const CLEAR_COLOR:uint = 4151151;
        public static const SCROLL_DOWN:int = 2;
        public static var STATIC_FILES_URL:String;
        public static const DIR8_NORTH_BIT:int = 1 << 4;
        public static const WINDOW_SIZE_FB_WIDTH:int = 760;
        public static const USER_DATA_STREET_BORDER_UP:int = 3;
        public static const UPDATE_REFRESH_MS:int = 5000;
        public static const USER_DATA_STREET_BORDER_DOWN:int = 4;
        public static const POPULATION_WAIT_TIME:int = 50000;
        public static const DIR4_SOUTH_WEST:int = 2;
        public static const NEIGHBOUR_SOUTH:int = 16;
        public static const STREET_MAP_WIDTH_4_FINAL:int = 256;
        public static const LOAD_SECTOR_MODE_START_ECONOMY:int = 0;
        public static const DEFAULT_BACKGROUND_CLEAR_COLOR:uint = 4151151;
        public static const NEIGHBOUR_EAST:int = 4;
        public static const PROTOKOLL_RESOURCE_CREATION_WRITE_TO_ARRAY_CHECK:Boolean = false;
        public static var USER_COUNTRY:String;
        public static const PROTOKOLL_RESOURCES_ORDER_CHECK:Boolean = false;
        public static var FORUM_URL:String;
        public static const STREET_MAP_MAX_USABLE_AREA_X:int = 63;
        public static const STREET_MAP_MAX_USABLE_AREA_Y:int = 124;
        public static var GAME_IDENTIFIER:String = "";
        public static var INVITE_URL:String;
        public static const DIR4_NORTH_EAST:int = 0;
        public static const STREET_MAP_HEIGHT_FINAL:int = 136;
        public static const DIR8_NORTH:int = 4;
        public static const ACTIVATE_CHAT:Boolean = true;
        public static const STREET_ELEMENT_NAME_string:String = "Street";
        public static const DIR4_SOUTH_EAST:int = 1;
        public static const DIR8_NORTH_EAST_BIT:int = 1 << 0;
        public static const ZERO_POINT:Point = new Point(0, 0);
        public static const GAMETICK_SYSTEM_POSTPROCESS_INCREASE:Number = 250;
        public static const MINEDEPOSITDEPLETEDCORN_NAME_string:String = "MineDepletedDepositCorn";
        public static const GAMETICK_PERIODIC_REFRESH_TIME:Number = 1000;
        public static const UPDATE_REFRESH:int = 5;
        public static const POPULATION_RESOURCE_NAME_string:String = "Population";
        public static const BARRACKS_NAME_string:String = "Barracks";
        public static const STREET_ZONE_SIZE_X:int = 59;
        public static const STREET_ZONE_SIZE_Y:int = 120;
        public static const DIR8_SOUTH_EAST_BIT:int = 1 << 1;
        public static const SECTOR_TYP_UNDEFINED:int = -1;
        public static var USE_EXTERNAL_SERVER:Boolean;
        public static const SCROLL_UP:int = 1;
        public static const RECTANGLE_MAP_MAX_USABLE_AREA_X:int = 33;
        public static const RECTANGLE_MAP_MAX_USABLE_AREA_Y:int = 32;
        public static var USE_BIG_BROTHER:Boolean;
        public static const PROVISIONHOUSE_NAME_string:String = "ProvisionHouse";
        public static const BUFF_BLOCKING_DURATION:int = 2000;
        public static var PAYMENT_URL:String;
        public static const WINDOW_SIZE_FB_HEIGHT:int = 595;
        public static const STREET_MAP_MIN_USABLE_AREA_X:int = 2;
        public static const STREET_MAP_MIN_USABLE_AREA_Y:int = 2;
        public static const STORE_ZONE_DELTA:Boolean = true;
        public static const DIR8_SOUTH_BIT:int = 1 << 6;
        public static const MAX_BUILDING_OFFSET:int = 20;
        public static const BUILDING_PROGRESS_SCALE_FACTOR:int = 10000;
        public static const STREET_DIR_NOF:int = 4;
        public static const FILENAME_GAME_SETTINGS:String = "game_settings.xml";
        public static const TAVERN_NAME_string:String = "Tavern";
        public static const STREET_MAP_WIDTH_FINAL_SHIFT:int = 6;
        public static var TRACKING_ID:String;
        public static const MAX_INT_VALUE:int = 2147483647;
        public static const FILTER_ACTIVATED:Boolean = true;
        public static const FADEIN_TIME:Number = 250;
        public static const MIN_UPGRADE_TIME_TO_MOVE_UPGRADING_BUILDING_FOR_GAMETICK:int = 10000;
        public static const GAMETICK_SYSTEM_POSTPROCESS_TIME_MAX:Number = 5000;
        public static var CHAT_SOCKET_URL:String;
        public static const DIR8_NORTH_WEST_BIT:int = 1 << 3;
        public static const RECTANGLE_MAP_MIN_USABLE_AREA_X:int = 0;
        public static const RECTANGLE_MAP_MIN_USABLE_AREA_Y:int = 0;
        public static const MAX_FREE_LANDSCAPES:int = 500;
        public static const VERSION_INFO:String = "V 0.315.257222-4878[Date: 20120514-1316]";
        public static const DIR8_SOUTH:int = 6;
        public static const ILLEGAL_INT_POS:int = -32767;
        public static const GAMETICK_PERIODIC_ZONE_REFRESH_TOLERANCE_TIME:Number = 5000;
        public static const STREET_ZONE_BORDER:int = 2;
        public static const DIR8_FILLED_BIT:int = 1 << 8;
        public static const GUI_LOWER_BORDER:uint = 8;
        public static const RECTANGLE_MAP_WIDTH:int = 34;
        public static const WOOD_RESOURCE_NAME_string:String = "Wood";
        public static const MAX_SPOOL_TIME:int = 8.64e+007;
        public static var CHAT_BOSH_URL:String;
        public static const BUILDING_INFO_ICON_TIME_FOR_DELAY:Number = 3.6e+006;
        public static const ACTIVATE_STREAMING:Boolean = true;
        public static const DIR8_EAST_BIT:int = 1 << 5;

        public function defines()
        {
            return;
        }// end function

    }
}
