//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.239
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodLesZ.SiedlerOnline.TradeListener.Language {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class locale_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locale_en() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GodLesZ.SiedlerOnline.TradeListener.Language.locale-en", typeof(locale_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beer ähnelt.
        /// </summary>
        internal static string Beer {
            get {
                return ResourceManager.GetString("Beer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bow ähnelt.
        /// </summary>
        internal static string Bow {
            get {
                return ResourceManager.GetString("Bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bread ähnelt.
        /// </summary>
        internal static string Bread {
            get {
                return ResourceManager.GetString("Bread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bronze ähnelt.
        /// </summary>
        internal static string Bronze {
            get {
                return ResourceManager.GetString("Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bronze Ore ähnelt.
        /// </summary>
        internal static string BronzeOre {
            get {
                return ResourceManager.GetString("BronzeOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bronze Sword ähnelt.
        /// </summary>
        internal static string BronzeSword {
            get {
                return ResourceManager.GetString("BronzeSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannon ähnelt.
        /// </summary>
        internal static string Cannon {
            get {
                return ResourceManager.GetString("Cannon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Carriage ähnelt.
        /// </summary>
        internal static string Carriage {
            get {
                return ResourceManager.GetString("Carriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Christmas Resource ähnelt.
        /// </summary>
        internal static string ChristmasResource {
            get {
                return ResourceManager.GetString("ChristmasResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coal ähnelt.
        /// </summary>
        internal static string Coal {
            get {
                return ResourceManager.GetString("Coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coin ähnelt.
        /// </summary>
        internal static string Coin {
            get {
                return ResourceManager.GetString("Coin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Corn ähnelt.
        /// </summary>
        internal static string Corn {
            get {
                return ResourceManager.GetString("Corn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crossbow ähnelt.
        /// </summary>
        internal static string Crossbow {
            get {
                return ResourceManager.GetString("Crossbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deer ähnelt.
        /// </summary>
        internal static string Deer {
            get {
                return ResourceManager.GetString("Deer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exotic Plank ähnelt.
        /// </summary>
        internal static string ExoticPlank {
            get {
                return ResourceManager.GetString("ExoticPlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exotic Wood ähnelt.
        /// </summary>
        internal static string ExoticWood {
            get {
                return ResourceManager.GetString("ExoticWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fish ähnelt.
        /// </summary>
        internal static string Fish {
            get {
                return ResourceManager.GetString("Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flour ähnelt.
        /// </summary>
        internal static string Flour {
            get {
                return ResourceManager.GetString("Flour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gold ähnelt.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gold Ore ähnelt.
        /// </summary>
        internal static string GoldOre {
            get {
                return ResourceManager.GetString("GoldOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Granite ähnelt.
        /// </summary>
        internal static string Granite {
            get {
                return ResourceManager.GetString("Granite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gun Powder ähnelt.
        /// </summary>
        internal static string GunPowder {
            get {
                return ResourceManager.GetString("GunPowder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HaloweenResource ähnelt.
        /// </summary>
        internal static string HaloweenResource {
            get {
                return ResourceManager.GetString("HaloweenResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Horse ähnelt.
        /// </summary>
        internal static string Horse {
            get {
                return ResourceManager.GetString("Horse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iron ähnelt.
        /// </summary>
        internal static string Iron {
            get {
                return ResourceManager.GetString("Iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iron Ore ähnelt.
        /// </summary>
        internal static string IronOre {
            get {
                return ResourceManager.GetString("IronOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iron Sword ähnelt.
        /// </summary>
        internal static string IronSword {
            get {
                return ResourceManager.GetString("IronSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Longbow ähnelt.
        /// </summary>
        internal static string Longbow {
            get {
                return ResourceManager.GetString("Longbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Map Part ähnelt.
        /// </summary>
        internal static string MapPart {
            get {
                return ResourceManager.GetString("MapPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marble ähnelt.
        /// </summary>
        internal static string Marble {
            get {
                return ResourceManager.GetString("Marble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meat ähnelt.
        /// </summary>
        internal static string Meat {
            get {
                return ResourceManager.GetString("Meat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plank ähnelt.
        /// </summary>
        internal static string Plank {
            get {
                return ResourceManager.GetString("Plank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Real Plank ähnelt.
        /// </summary>
        internal static string RealPlank {
            get {
                return ResourceManager.GetString("RealPlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Real Wood ähnelt.
        /// </summary>
        internal static string RealWood {
            get {
                return ResourceManager.GetString("RealWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Salpeter ähnelt.
        /// </summary>
        internal static string Salpeter {
            get {
                return ResourceManager.GetString("Salpeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sausage ähnelt.
        /// </summary>
        internal static string Sausage {
            get {
                return ResourceManager.GetString("Sausage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steel ähnelt.
        /// </summary>
        internal static string Steel {
            get {
                return ResourceManager.GetString("Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steel Sword ähnelt.
        /// </summary>
        internal static string SteelSword {
            get {
                return ResourceManager.GetString("SteelSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stone ähnelt.
        /// </summary>
        internal static string Stone {
            get {
                return ResourceManager.GetString("Stone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titanium ähnelt.
        /// </summary>
        internal static string Titanium {
            get {
                return ResourceManager.GetString("Titanium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titanium Ore ähnelt.
        /// </summary>
        internal static string TitaniumOre {
            get {
                return ResourceManager.GetString("TitaniumOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titanium Sword ähnelt.
        /// </summary>
        internal static string TitaniumSword {
            get {
                return ResourceManager.GetString("TitaniumSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tool ähnelt.
        /// </summary>
        internal static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ratio: \t\t\t{0}\n\nAverage:\t\t{1}\nNumber of values:\t{2}\nLower bound:\t\t{3} ({4})\nUpper bound:\t\t{5} ({6})\n ähnelt.
        /// </summary>
        internal static string TradeListRatioToolTip {
            get {
                return ResourceManager.GetString("TradeListRatioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Water ähnelt.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wheel ähnelt.
        /// </summary>
        internal static string Wheel {
            get {
                return ResourceManager.GetString("Wheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wood ähnelt.
        /// </summary>
        internal static string Wood {
            get {
                return ResourceManager.GetString("Wood", resourceCulture);
            }
        }
    }
}
