//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.239
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodLesZ.SiedlerOnline.TradeListener.Language {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class locale_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locale_de() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GodLesZ.SiedlerOnline.TradeListener.Language.locale-de", typeof(locale_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bier ähnelt.
        /// </summary>
        internal static string Beer {
            get {
                return ResourceManager.GetString("Beer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bogen ähnelt.
        /// </summary>
        internal static string Bow {
            get {
                return ResourceManager.GetString("Bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brot ähnelt.
        /// </summary>
        internal static string Bread {
            get {
                return ResourceManager.GetString("Bread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bronze ähnelt.
        /// </summary>
        internal static string Bronze {
            get {
                return ResourceManager.GetString("Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bronze Erz ähnelt.
        /// </summary>
        internal static string BronzeOre {
            get {
                return ResourceManager.GetString("BronzeOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bronze Schwert ähnelt.
        /// </summary>
        internal static string BronzeSword {
            get {
                return ResourceManager.GetString("BronzeSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kanone ähnelt.
        /// </summary>
        internal static string Cannon {
            get {
                return ResourceManager.GetString("Cannon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Karren ähnelt.
        /// </summary>
        internal static string Carriage {
            get {
                return ResourceManager.GetString("Carriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weihnachtsgeschenk ähnelt.
        /// </summary>
        internal static string ChristmasResource {
            get {
                return ResourceManager.GetString("ChristmasResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kohle ähnelt.
        /// </summary>
        internal static string Coal {
            get {
                return ResourceManager.GetString("Coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Münze ähnelt.
        /// </summary>
        internal static string Coin {
            get {
                return ResourceManager.GetString("Coin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Getreide ähnelt.
        /// </summary>
        internal static string Corn {
            get {
                return ResourceManager.GetString("Corn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Armbrust ähnelt.
        /// </summary>
        internal static string Crossbow {
            get {
                return ResourceManager.GetString("Crossbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hirsch ähnelt.
        /// </summary>
        internal static string Deer {
            get {
                return ResourceManager.GetString("Deer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edelholz ähnelt.
        /// </summary>
        internal static string ExoticPlank {
            get {
                return ResourceManager.GetString("ExoticPlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edelholzbrett ähnelt.
        /// </summary>
        internal static string ExoticWood {
            get {
                return ResourceManager.GetString("ExoticWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fisch ähnelt.
        /// </summary>
        internal static string Fish {
            get {
                return ResourceManager.GetString("Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mehl ähnelt.
        /// </summary>
        internal static string Flour {
            get {
                return ResourceManager.GetString("Flour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Goldbarren ähnelt.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Golderz ähnelt.
        /// </summary>
        internal static string GoldOre {
            get {
                return ResourceManager.GetString("GoldOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Granit ähnelt.
        /// </summary>
        internal static string Granite {
            get {
                return ResourceManager.GetString("Granite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schießpulver ähnelt.
        /// </summary>
        internal static string GunPowder {
            get {
                return ResourceManager.GetString("GunPowder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kürbis ähnelt.
        /// </summary>
        internal static string HaloweenResource {
            get {
                return ResourceManager.GetString("HaloweenResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pferd ähnelt.
        /// </summary>
        internal static string Horse {
            get {
                return ResourceManager.GetString("Horse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eisen ähnelt.
        /// </summary>
        internal static string Iron {
            get {
                return ResourceManager.GetString("Iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eisenerz ähnelt.
        /// </summary>
        internal static string IronOre {
            get {
                return ResourceManager.GetString("IronOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eisenschwert ähnelt.
        /// </summary>
        internal static string IronSword {
            get {
                return ResourceManager.GetString("IronSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Langbogen ähnelt.
        /// </summary>
        internal static string Longbow {
            get {
                return ResourceManager.GetString("Longbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kartenfragment ähnelt.
        /// </summary>
        internal static string MapPart {
            get {
                return ResourceManager.GetString("MapPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marmor ähnelt.
        /// </summary>
        internal static string Marble {
            get {
                return ResourceManager.GetString("Marble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fleisch ähnelt.
        /// </summary>
        internal static string Meat {
            get {
                return ResourceManager.GetString("Meat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nadelholzbrett ähnelt.
        /// </summary>
        internal static string Plank {
            get {
                return ResourceManager.GetString("Plank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laubholzbrett ähnelt.
        /// </summary>
        internal static string RealPlank {
            get {
                return ResourceManager.GetString("RealPlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laubholz ähnelt.
        /// </summary>
        internal static string RealWood {
            get {
                return ResourceManager.GetString("RealWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Salpeter ähnelt.
        /// </summary>
        internal static string Salpeter {
            get {
                return ResourceManager.GetString("Salpeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fleischwurst ähnelt.
        /// </summary>
        internal static string Sausage {
            get {
                return ResourceManager.GetString("Sausage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stahl ähnelt.
        /// </summary>
        internal static string Steel {
            get {
                return ResourceManager.GetString("Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stahlschwert ähnelt.
        /// </summary>
        internal static string SteelSword {
            get {
                return ResourceManager.GetString("SteelSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stein ähnelt.
        /// </summary>
        internal static string Stone {
            get {
                return ResourceManager.GetString("Stone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titanium ähnelt.
        /// </summary>
        internal static string Titanium {
            get {
                return ResourceManager.GetString("Titanium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titaniumerz ähnelt.
        /// </summary>
        internal static string TitaniumOre {
            get {
                return ResourceManager.GetString("TitaniumOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titaniumschwert ähnelt.
        /// </summary>
        internal static string TitaniumSword {
            get {
                return ResourceManager.GetString("TitaniumSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Werkzeug ähnelt.
        /// </summary>
        internal static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ratio: \t\t\t{0}\n\nDurchschnitt:\t\t{1}\nAnzahl Werte:\t{2}\nNiedrigster Wert:\t\t{3} ({4})\nHöchster Wert:\t\t{5} ({6})\n ähnelt.
        /// </summary>
        internal static string TradeListRatioToolTip {
            get {
                return ResourceManager.GetString("TradeListRatioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wasser ähnelt.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rad ähnelt.
        /// </summary>
        internal static string Wheel {
            get {
                return ResourceManager.GetString("Wheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nadelholz ähnelt.
        /// </summary>
        internal static string Wood {
            get {
                return ResourceManager.GetString("Wood", resourceCulture);
            }
        }
    }
}
