//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodLesZ.BlubbRO.Patcher.Properties {
	using System;


	/// <summary>
	///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
	/// </summary>
	// Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
	// -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
	// Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
	// mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}

		/// <summary>
		///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Iro.Patcher.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
		///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		internal static System.Drawing.Bitmap background {
			get {
				object obj = ResourceManager.GetObject("background", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap btn_forum {
			get {
				object obj = ResourceManager.GetObject("btn_forum", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap btn_forumHover {
			get {
				object obj = ResourceManager.GetObject("btn_forumHover", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap btn_game {
			get {
				object obj = ResourceManager.GetObject("btn_game", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap btn_gameHover {
			get {
				object obj = ResourceManager.GetObject("btn_gameHover", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap progressbar {
			get {
				object obj = ResourceManager.GetObject("progressbar", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap state_offline {
			get {
				object obj = ResourceManager.GetObject("state_offline", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap state_online {
			get {
				object obj = ResourceManager.GetObject("state_online", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Zahl_0 {
			get {
				object obj = ResourceManager.GetObject("Zahl_0", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Zahl_1 {
			get {
				object obj = ResourceManager.GetObject("Zahl_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Zahl_2 {
			get {
				object obj = ResourceManager.GetObject("Zahl_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Zahl_3 {
			get {
				object obj = ResourceManager.GetObject("Zahl_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Zahl_4 {
			get {
				object obj = ResourceManager.GetObject("Zahl_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Zahl_5 {
			get {
				object obj = ResourceManager.GetObject("Zahl_5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Zahl_6 {
			get {
				object obj = ResourceManager.GetObject("Zahl_6", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Zahl_7 {
			get {
				object obj = ResourceManager.GetObject("Zahl_7", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Zahl_8 {
			get {
				object obj = ResourceManager.GetObject("Zahl_8", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Zahl_9 {
			get {
				object obj = ResourceManager.GetObject("Zahl_9", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
