/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RohstoffVorkommen.java
 *
 * Created on 14.05.2011, 17:12:39
 */

package siedleronlineproxy.forms.deposits;

/**
 *
 * @author nspecht
 */
public class RohstoffVorkommen extends javax.swing.JPanel {
    private static RohstoffVorkommen instance = null;
    public static RohstoffVorkommen getInstance() {
        return RohstoffVorkommen.instance;
    }

    /** Creates new form RohstoffVorkommen */
    public RohstoffVorkommen() {
        initComponents();
        RohstoffVorkommen.instance = this;
        this.depositTableWood.filter = "Wood";
        this.depositTableRealWood.filter = "RealWood";
        this.depositTableWater.filter = "Water";
        this.depositTableStone.filter = "Stone";
        this.depositTableMeat.filter = "Meat";
        this.depositTableMarble.filter = "Marble";
        this.depositTableIronOre.filter = "IronOre";
        this.depositTableFish.filter = "Fish";
        this.depositTableCorn.filter = "Corn";
        this.depositTableBronzeOre.filter = "BronzeOre";
        this.depositTableCoal.filter = "Coal";
        this.depositTableGoldOre.filter = "GoldOre";
        this.depositTableAktion.filter = "HalloweenResource";

    }

    public void update() {
        this.depositTableWood.update();
        this.depositTableRealWood.update();
        this.depositTableWater.update();
        this.depositTableStone.update();
        this.depositTableMeat.update();
        this.depositTableMarble.update();
        this.depositTableIronOre.update();
        this.depositTableFish.update();
        this.depositTableCorn.update();
        this.depositTableBronzeOre.update();
        this.depositTableGoldOre.update();
        this.depositTableCoal.update();
        this.depositTableALL.update();
        this.depositTableAktion.update();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPaneWood = new javax.swing.JScrollPane();
        depositTableWood = new siedleronlineproxy.forms.deposits.DepositTable();
        jScrollPaneStone = new javax.swing.JScrollPane();
        depositTableStone = new siedleronlineproxy.forms.deposits.DepositTable();
        jScrollPaneRealWood = new javax.swing.JScrollPane();
        depositTableRealWood = new siedleronlineproxy.forms.deposits.DepositTable();
        jScrollPaneMarble = new javax.swing.JScrollPane();
        depositTableMarble = new siedleronlineproxy.forms.deposits.DepositTable();
        jScrollPaneWater = new javax.swing.JScrollPane();
        depositTableWater = new siedleronlineproxy.forms.deposits.DepositTable();
        jScrollPaneFish = new javax.swing.JScrollPane();
        depositTableFish = new siedleronlineproxy.forms.deposits.DepositTable();
        jScrollPaneCorn = new javax.swing.JScrollPane();
        depositTableCorn = new siedleronlineproxy.forms.deposits.DepositTable();
        jScrollPaneMeat = new javax.swing.JScrollPane();
        depositTableMeat = new siedleronlineproxy.forms.deposits.DepositTable();
        jScrollPaneBronzeOre = new javax.swing.JScrollPane();
        depositTableBronzeOre = new siedleronlineproxy.forms.deposits.DepositTable();
        jScrollPaneIronOre = new javax.swing.JScrollPane();
        depositTableIronOre = new siedleronlineproxy.forms.deposits.DepositTable();
        jScrollPaneGold = new javax.swing.JScrollPane();
        depositTableGoldOre = new siedleronlineproxy.forms.deposits.DepositTable();
        jScrollPaneCoal = new javax.swing.JScrollPane();
        depositTableCoal = new siedleronlineproxy.forms.deposits.DepositTable();
        jScrollPaneAktion = new javax.swing.JScrollPane();
        depositTableAktion = new siedleronlineproxy.forms.deposits.DepositTable();
        jScrollPaneALL = new javax.swing.JScrollPane();
        depositTableALL = new siedleronlineproxy.forms.deposits.DepositTable();

        setName("Form"); // NOI18N
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jScrollPaneWood.setName("jScrollPaneWood"); // NOI18N

        depositTableWood.setName("depositTableWood"); // NOI18N
        jScrollPaneWood.setViewportView(depositTableWood);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(siedleronlineproxy.SiedlerOnlineProxyApp.class).getContext().getResourceMap(RohstoffVorkommen.class);
        jTabbedPane1.addTab(resourceMap.getString("jScrollPaneWood.TabConstraints.tabTitle"), resourceMap.getIcon("jScrollPaneWood.TabConstraints.tabIcon"), jScrollPaneWood); // NOI18N

        jScrollPaneStone.setName("jScrollPaneStone"); // NOI18N

        depositTableStone.setName("depositTableStone"); // NOI18N
        jScrollPaneStone.setViewportView(depositTableStone);

        jTabbedPane1.addTab(resourceMap.getString("jScrollPaneStone.TabConstraints.tabTitle"), resourceMap.getIcon("jScrollPaneStone.TabConstraints.tabIcon"), jScrollPaneStone); // NOI18N

        jScrollPaneRealWood.setName("jScrollPaneRealWood"); // NOI18N

        depositTableRealWood.setName("depositTableRealWood"); // NOI18N
        jScrollPaneRealWood.setViewportView(depositTableRealWood);

        jTabbedPane1.addTab(resourceMap.getString("jScrollPaneRealWood.TabConstraints.tabTitle"), resourceMap.getIcon("jScrollPaneRealWood.TabConstraints.tabIcon"), jScrollPaneRealWood); // NOI18N

        jScrollPaneMarble.setName("jScrollPaneMarble"); // NOI18N

        depositTableMarble.setName("depositTableMarble"); // NOI18N
        jScrollPaneMarble.setViewportView(depositTableMarble);

        jTabbedPane1.addTab(resourceMap.getString("jScrollPaneMarble.TabConstraints.tabTitle"), resourceMap.getIcon("jScrollPaneMarble.TabConstraints.tabIcon"), jScrollPaneMarble); // NOI18N

        jScrollPaneWater.setName("jScrollPaneWater"); // NOI18N

        depositTableWater.setName("depositTableWater"); // NOI18N
        jScrollPaneWater.setViewportView(depositTableWater);

        jTabbedPane1.addTab(resourceMap.getString("jScrollPaneWater.TabConstraints.tabTitle"), resourceMap.getIcon("jScrollPaneWater.TabConstraints.tabIcon"), jScrollPaneWater); // NOI18N

        jScrollPaneFish.setName("jScrollPaneFish"); // NOI18N

        depositTableFish.setName("depositTableFish"); // NOI18N
        jScrollPaneFish.setViewportView(depositTableFish);

        jTabbedPane1.addTab(resourceMap.getString("jScrollPaneFish.TabConstraints.tabTitle"), resourceMap.getIcon("jScrollPaneFish.TabConstraints.tabIcon"), jScrollPaneFish); // NOI18N

        jScrollPaneCorn.setName("jScrollPaneCorn"); // NOI18N

        depositTableCorn.setName("depositTableCorn"); // NOI18N
        jScrollPaneCorn.setViewportView(depositTableCorn);

        jTabbedPane1.addTab(resourceMap.getString("jScrollPaneCorn.TabConstraints.tabTitle"), resourceMap.getIcon("jScrollPaneCorn.TabConstraints.tabIcon"), jScrollPaneCorn); // NOI18N

        jScrollPaneMeat.setName("jScrollPaneMeat"); // NOI18N

        depositTableMeat.setName("depositTableMeat"); // NOI18N
        jScrollPaneMeat.setViewportView(depositTableMeat);

        jTabbedPane1.addTab(resourceMap.getString("jScrollPaneMeat.TabConstraints.tabTitle"), resourceMap.getIcon("jScrollPaneMeat.TabConstraints.tabIcon"), jScrollPaneMeat); // NOI18N

        jScrollPaneBronzeOre.setName("jScrollPaneBronzeOre"); // NOI18N

        depositTableBronzeOre.setName("depositTableBronzeOre"); // NOI18N
        jScrollPaneBronzeOre.setViewportView(depositTableBronzeOre);

        jTabbedPane1.addTab(resourceMap.getString("jScrollPaneBronzeOre.TabConstraints.tabTitle"), resourceMap.getIcon("jScrollPaneBronzeOre.TabConstraints.tabIcon"), jScrollPaneBronzeOre); // NOI18N

        jScrollPaneIronOre.setName("jScrollPaneIronOre"); // NOI18N

        depositTableIronOre.setName("depositTableIronOre"); // NOI18N
        jScrollPaneIronOre.setViewportView(depositTableIronOre);

        jTabbedPane1.addTab(resourceMap.getString("jScrollPaneIronOre.TabConstraints.tabTitle"), resourceMap.getIcon("jScrollPaneIronOre.TabConstraints.tabIcon"), jScrollPaneIronOre); // NOI18N

        jScrollPaneGold.setName("jScrollPaneGold"); // NOI18N

        depositTableGoldOre.setName("depositTableGoldOre"); // NOI18N
        jScrollPaneGold.setViewportView(depositTableGoldOre);

        jTabbedPane1.addTab(resourceMap.getString("jScrollPaneGold.TabConstraints.tabTitle"), resourceMap.getIcon("jScrollPaneGold.TabConstraints.tabIcon"), jScrollPaneGold); // NOI18N

        jScrollPaneCoal.setName("jScrollPaneCoal"); // NOI18N

        depositTableCoal.setName("depositTableCoal"); // NOI18N
        jScrollPaneCoal.setViewportView(depositTableCoal);

        jTabbedPane1.addTab(resourceMap.getString("jScrollPaneCoal.TabConstraints.tabTitle"), resourceMap.getIcon("jScrollPaneCoal.TabConstraints.tabIcon"), jScrollPaneCoal); // NOI18N

        jScrollPaneAktion.setName("jScrollPaneAktion"); // NOI18N

        depositTableAktion.setName("depositTableAktion"); // NOI18N
        jScrollPaneAktion.setViewportView(depositTableAktion);

        jTabbedPane1.addTab(resourceMap.getString("jScrollPaneAktion.TabConstraints.tabTitle"), resourceMap.getIcon("jScrollPaneAktion.TabConstraints.tabIcon"), jScrollPaneAktion); // NOI18N

        jScrollPaneALL.setName("jScrollPaneALL"); // NOI18N

        depositTableALL.setName("depositTableALL"); // NOI18N
        jScrollPaneALL.setViewportView(depositTableALL);

        jTabbedPane1.addTab(resourceMap.getString("jScrollPaneALL.TabConstraints.tabTitle"), resourceMap.getIcon("jScrollPaneALL.TabConstraints.tabIcon"), jScrollPaneALL); // NOI18N

        add(jTabbedPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private siedleronlineproxy.forms.deposits.DepositTable depositTableALL;
    private siedleronlineproxy.forms.deposits.DepositTable depositTableAktion;
    private siedleronlineproxy.forms.deposits.DepositTable depositTableBronzeOre;
    private siedleronlineproxy.forms.deposits.DepositTable depositTableCoal;
    private siedleronlineproxy.forms.deposits.DepositTable depositTableCorn;
    private siedleronlineproxy.forms.deposits.DepositTable depositTableFish;
    private siedleronlineproxy.forms.deposits.DepositTable depositTableGoldOre;
    private siedleronlineproxy.forms.deposits.DepositTable depositTableIronOre;
    private siedleronlineproxy.forms.deposits.DepositTable depositTableMarble;
    private siedleronlineproxy.forms.deposits.DepositTable depositTableMeat;
    private siedleronlineproxy.forms.deposits.DepositTable depositTableRealWood;
    private siedleronlineproxy.forms.deposits.DepositTable depositTableStone;
    private siedleronlineproxy.forms.deposits.DepositTable depositTableWater;
    private siedleronlineproxy.forms.deposits.DepositTable depositTableWood;
    private javax.swing.JScrollPane jScrollPaneALL;
    private javax.swing.JScrollPane jScrollPaneAktion;
    private javax.swing.JScrollPane jScrollPaneBronzeOre;
    private javax.swing.JScrollPane jScrollPaneCoal;
    private javax.swing.JScrollPane jScrollPaneCorn;
    private javax.swing.JScrollPane jScrollPaneFish;
    private javax.swing.JScrollPane jScrollPaneGold;
    private javax.swing.JScrollPane jScrollPaneIronOre;
    private javax.swing.JScrollPane jScrollPaneMarble;
    private javax.swing.JScrollPane jScrollPaneMeat;
    private javax.swing.JScrollPane jScrollPaneRealWood;
    private javax.swing.JScrollPane jScrollPaneStone;
    private javax.swing.JScrollPane jScrollPaneWater;
    private javax.swing.JScrollPane jScrollPaneWood;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
