//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.239
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodLesZ.SettlerOnline.FightSimulator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GodLesZ.SettlerOnline.FightSimulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1291735405_folderopen1 {
            get {
                object obj = ResourceManager.GetObject("_1291735405_folderopen1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1291735424_folder_open_add {
            get {
                object obj = ResourceManager.GetObject("_1291735424_folder_open_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1291735436_trash_can2_delete {
            get {
                object obj = ResourceManager.GetObject("_1291735436_trash_can2_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1291735548_save {
            get {
                object obj = ResourceManager.GetObject("_1291735548_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1291735608_Rename_Document {
            get {
                object obj = ResourceManager.GetObject("_1291735608_Rename_Document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Armbrustschuetze {
            get {
                object obj = ResourceManager.GetObject("Armbrustschuetze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bert {
            get {
                object obj = ResourceManager.GetObject("Bert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bogenschuetze {
            get {
                object obj = ResourceManager.GetObject("Bogenschuetze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chuck {
            get {
                object obj = ResourceManager.GetObject("Chuck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DwW {
            get {
                object obj = ResourceManager.GetObject("DwW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Elitesoldat {
            get {
                object obj = ResourceManager.GetObject("Elitesoldat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap General_s {
            get {
                object obj = ResourceManager.GetObject("General_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kanonier {
            get {
                object obj = ResourceManager.GetObject("Kanonier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Langbogenschuetze {
            get {
                object obj = ResourceManager.GetObject("Langbogenschuetze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MG {
            get {
                object obj = ResourceManager.GetObject("MG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Miliz {
            get {
                object obj = ResourceManager.GetObject("Miliz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pluenderer {
            get {
                object obj = ResourceManager.GetObject("Pluenderer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Raufbold {
            get {
                object obj = ResourceManager.GetObject("Raufbold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Reiterei {
            get {
                object obj = ResourceManager.GetObject("Reiterei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rekrut {
            get {
                object obj = ResourceManager.GetObject("Rekrut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Schlaeger {
            get {
                object obj = ResourceManager.GetObject("Schlaeger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Soldat {
            get {
                object obj = ResourceManager.GetObject("Soldat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Steinwerfer {
            get {
                object obj = ResourceManager.GetObject("Steinwerfer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stinktier {
            get {
                object obj = ResourceManager.GetObject("Stinktier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wachhund {
            get {
                object obj = ResourceManager.GetObject("Wachhund", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Waldleaufer {
            get {
                object obj = ResourceManager.GetObject("Waldleaufer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;div id=&quot;container1&quot;&gt;
        ///&lt;div align=&quot;center&quot;&gt;&lt;font size=&quot;6&quot;&gt;&lt;b&gt;&lt;u&gt;The War Guide&lt;/u&gt;&lt;/b&gt;&lt;/font&gt;&lt;b&gt;&lt;br /&gt;
        ///by TheMachine&lt;/b&gt;&lt;br /&gt;
        ///(Version 1.0.2)&lt;/div&gt;&lt;br /&gt;
        ///
        ///&lt;p&gt;Diese Erklärung ist eine empirische Beschreibung des Kampfsystem und kann noch Fehler enthalten!
        ///&lt;/p&gt;&lt;p&gt;&lt;br /&gt;
        ///&lt;/p&gt;&lt;p&gt;Im wesentlichen ist es ein rundenbasierendes System, welches auf den Hitpoints (HP) und dem Schaden einer Einheit aufbaut. Sobald eine Einheit 0 HP hat, ist diese (wie ihr euch schon denken könnt) tot.&lt;br /&gt;
        ///Welche Einheit zuerst [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string WarGuide {
            get {
                return ResourceManager.GetString("WarGuide", resourceCulture);
            }
        }
    }
}
