//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18034
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodLesZ.Library.MySql.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GodLesZ.Library.MySql.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Improper MySqlCommandBuilder state: adapter is null ähnelt.
        /// </summary>
        internal static string AdapterIsNull {
            get {
                return ResourceManager.GetString("AdapterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Improper MySqlCommandBuilder state: adapter&apos;s SelectCommand is null ähnelt.
        /// </summary>
        internal static string AdapterSelectIsNull {
            get {
                return ResourceManager.GetString("AdapterSelectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid attempt to access a field before calling Read() ähnelt.
        /// </summary>
        internal static string AttemptToAccessBeforeRead {
            get {
                return ResourceManager.GetString("AttemptToAccessBeforeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version string not in acceptable format ähnelt.
        /// </summary>
        internal static string BadVersionFormat {
            get {
                return ResourceManager.GetString("BadVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  The buffer cannot be null ähnelt.
        /// </summary>
        internal static string BufferCannotBeNull {
            get {
                return ResourceManager.GetString("BufferCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Buffer is not large enough ähnelt.
        /// </summary>
        internal static string BufferNotLargeEnough {
            get {
                return ResourceManager.GetString("BufferNotLargeEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Canceling an executing query requires MySQL 5.0 or higher. ähnelt.
        /// </summary>
        internal static string CancelNeeds50 {
            get {
                return ResourceManager.GetString("CancelNeeds50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Canceling an active query is only supported on MySQL 5.0.0 and above.  ähnelt.
        /// </summary>
        internal static string CancelNotSupported {
            get {
                return ResourceManager.GetString("CancelNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MySqlCommandBuilder does not support multi-table statements ähnelt.
        /// </summary>
        internal static string CBMultiTableNotSupported {
            get {
                return ResourceManager.GetString("CBMultiTableNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MySqlCommandBuilder cannot operate on tables with no unique or key columns ähnelt.
        /// </summary>
        internal static string CBNoKeyColumn {
            get {
                return ResourceManager.GetString("CBNoKeyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chaos isolation level is not supported ähnelt.
        /// </summary>
        internal static string ChaosNotSupported {
            get {
                return ResourceManager.GetString("ChaosNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The CommandText property has not been properly initialized. ähnelt.
        /// </summary>
        internal static string CommandTextNotInitialized {
            get {
                return ResourceManager.GetString("CommandTextNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The connection is already open. ähnelt.
        /// </summary>
        internal static string ConnectionAlreadyOpen {
            get {
                return ResourceManager.GetString("ConnectionAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection unexpectedly terminated. ähnelt.
        /// </summary>
        internal static string ConnectionBroken {
            get {
                return ResourceManager.GetString("ConnectionBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection must be valid and open ähnelt.
        /// </summary>
        internal static string ConnectionMustBeOpen {
            get {
                return ResourceManager.GetString("ConnectionMustBeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The connection is not open. ähnelt.
        /// </summary>
        internal static string ConnectionNotOpen {
            get {
                return ResourceManager.GetString("ConnectionNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The connection property has not been set or is null. ähnelt.
        /// </summary>
        internal static string ConnectionNotSet {
            get {
                return ResourceManager.GetString("ConnectionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not find specified column in results: {0} ähnelt.
        /// </summary>
        internal static string CouldNotFindColumnName {
            get {
                return ResourceManager.GetString("CouldNotFindColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Count cannot be negative ähnelt.
        /// </summary>
        internal static string CountCannotBeNegative {
            get {
                return ResourceManager.GetString("CountCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SetLength is not a valid operation on CompressedStream ähnelt.
        /// </summary>
        internal static string CSNoSetLength {
            get {
                return ResourceManager.GetString("CSNoSetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given value was not in a supported format. ähnelt.
        /// </summary>
        internal static string DataNotInSupportedFormat {
            get {
                return ResourceManager.GetString("DataNotInSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is already an open DataReader associated with this Connection which must be closed first. ähnelt.
        /// </summary>
        internal static string DataReaderOpen {
            get {
                return ResourceManager.GetString("DataReaderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The default connection encoding was not found. Please report this as a bug along with your connection string and system details. ähnelt.
        /// </summary>
        internal static string DefaultEncodingNotFound {
            get {
                return ResourceManager.GetString("DefaultEncodingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MySQL Connector/Net does not currently support distributed transactions. ähnelt.
        /// </summary>
        internal static string DistributedTxnNotSupported {
            get {
                return ResourceManager.GetString("DistributedTxnNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error creating socket connection ähnelt.
        /// </summary>
        internal static string ErrorCreatingSocket {
            get {
                return ResourceManager.GetString("ErrorCreatingSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fatal error encountered during command execution. ähnelt.
        /// </summary>
        internal static string FatalErrorDuringExecute {
            get {
                return ResourceManager.GetString("FatalErrorDuringExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fatal error encountered during data read. ähnelt.
        /// </summary>
        internal static string FatalErrorDuringRead {
            get {
                return ResourceManager.GetString("FatalErrorDuringRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fatal error encountered attempting to read the resultset. ähnelt.
        /// </summary>
        internal static string FatalErrorReadingResult {
            get {
                return ResourceManager.GetString("FatalErrorReadingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From index and length use more bytes than from contains ähnelt.
        /// </summary>
        internal static string FromAndLengthTooBig {
            get {
                return ResourceManager.GetString("FromAndLengthTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From index must be a valid index inside the from buffer ähnelt.
        /// </summary>
        internal static string FromIndexMustBeValid {
            get {
                return ResourceManager.GetString("FromIndexMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Call to GetHostEntry failed after {0} while querying for hostname &apos;{1}&apos;: SocketErrorCode={2}, ErrorCode={3}, NativeErrorCode={4}. ähnelt.
        /// </summary>
        internal static string GetHostEntryFailed {
            get {
                return ResourceManager.GetString("GetHostEntryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retrieving procedure metadata for {0} from server. ähnelt.
        /// </summary>
        internal static string HardProcQuery {
            get {
                return ResourceManager.GetString("HardProcQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value has an unsupported format. ähnelt.
        /// </summary>
        internal static string ImproperValueFormat {
            get {
                return ResourceManager.GetString("ImproperValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An incorrect response was received from the server. ähnelt.
        /// </summary>
        internal static string IncorrectTransmission {
            get {
                return ResourceManager.GetString("IncorrectTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index and length use more bytes than to has room for ähnelt.
        /// </summary>
        internal static string IndexAndLengthTooBig {
            get {
                return ResourceManager.GetString("IndexAndLengthTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index must be a valid position in the buffer ähnelt.
        /// </summary>
        internal static string IndexMustBeValid {
            get {
                return ResourceManager.GetString("IndexMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have specified an invalid column ordinal. ähnelt.
        /// </summary>
        internal static string InvalidColumnOrdinal {
            get {
                return ResourceManager.GetString("InvalidColumnOrdinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The requested value &apos;{0}&apos; is invalid for the given keyword &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string InvalidConnectionStringValue {
            get {
                return ResourceManager.GetString("InvalidConnectionStringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Procedure or function &apos;{0}&apos; cannot be found in database &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string InvalidProcName {
            get {
                return ResourceManager.GetString("InvalidProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is an illegal value for a boolean option. ähnelt.
        /// </summary>
        internal static string InvalidValueForBoolean {
            get {
                return ResourceManager.GetString("InvalidValueForBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keyword does not allow null values. ähnelt.
        /// </summary>
        internal static string KeywordNoNull {
            get {
                return ResourceManager.GetString("KeywordNoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keyword not supported. ähnelt.
        /// </summary>
        internal static string KeywordNotSupported {
            get {
                return ResourceManager.GetString("KeywordNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ACCESSIBLE
        ///ADD
        ///ALL
        ///ALTER
        ///ANALYZE
        ///AND
        ///AS
        ///ASC
        ///ASENSITIVE
        ///BEFORE
        ///BETWEEN
        ///BIGINT
        ///BINARY
        ///BLOB
        ///BOTH
        ///BY
        ///CALL
        ///CASCADE
        ///CASE
        ///CHANGE
        ///CHAR
        ///CHARACTER
        ///CHECK
        ///COLLATE
        ///COLUMN
        ///CONDITION
        ///CONNECTION
        ///CONSTRAINT
        ///CONTINUE
        ///CONVERT
        ///CREATE
        ///CROSS
        ///CURRENT_DATE
        ///CURRENT_TIME
        ///CURRENT_TIMESTAMP
        ///CURRENT_USER
        ///CURSOR
        ///DATABASE
        ///DATABASES
        ///DAY_HOUR
        ///DAY_MICROSECOND
        ///DAY_MINUTE
        ///DAY_SECOND
        ///DEC
        ///DECIMAL
        ///DECLARE
        ///DEFAULT
        ///DELAYED
        ///DELETE
        ///DESC
        ///DESCRIBE
        ///DETERMINISTIC
        ///DISTINCT
        ///DISTINCTROW
        ///DIV
        ///DOUBLE
        ///DROP
        ///DUAL
        ///EACH
        ///ELSE
        ///ELSEIF
        ///ENCLOSED
        ///ESCAPED
        ///EXISTS
        ///EXIT
        ///EXP [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string keywords {
            get {
                return ResourceManager.GetString("keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MixingUpdatedRowSource ähnelt.
        /// </summary>
        internal static string MixingUpdatedRowSource {
            get {
                return ResourceManager.GetString("MixingUpdatedRowSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die INTERNAL ERROR:  More than one output parameter row detected. ähnelt.
        /// </summary>
        internal static string MoreThanOneOPRow {
            get {
                return ResourceManager.GetString("MoreThanOneOPRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multiple simultaneous connections or connections with different connection strings inside the same transaction are not currently supported. ähnelt.
        /// </summary>
        internal static string MultipleConnectionsInTransactionNotSupported {
            get {
                return ResourceManager.GetString("MultipleConnectionsInTransactionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NamedPipeStream does not support seeking ähnelt.
        /// </summary>
        internal static string NamedPipeNoSeek {
            get {
                return ResourceManager.GetString("NamedPipeNoSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NamedPipeStream doesn&apos;t support SetLength ähnelt.
        /// </summary>
        internal static string NamedPipeNoSetLength {
            get {
                return ResourceManager.GetString("NamedPipeNoSetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid attempt to call NextResult when the reader is closed. ähnelt.
        /// </summary>
        internal static string NextResultIsClosed {
            get {
                return ResourceManager.GetString("NextResultIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When calling stored procedures and &apos;Use Procedure Bodies&apos; is false, all parameters must have their type explicitly set. ähnelt.
        /// </summary>
        internal static string NoBodiesAndTypeNotSet {
            get {
                return ResourceManager.GetString("NoBodiesAndTypeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nested transactions are not supported. ähnelt.
        /// </summary>
        internal static string NoNestedTransactions {
            get {
                return ResourceManager.GetString("NoNestedTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The host {0} does not support SSL connections. ähnelt.
        /// </summary>
        internal static string NoServerSSLSupport {
            get {
                return ResourceManager.GetString("NoServerSSLSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The object is not open or has been disposed. ähnelt.
        /// </summary>
        internal static string ObjectDisposed {
            get {
                return ResourceManager.GetString("ObjectDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Offset cannot be negative ähnelt.
        /// </summary>
        internal static string OffsetCannotBeNegative {
            get {
                return ResourceManager.GetString("OffsetCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset must be a valid position in buffer ähnelt.
        /// </summary>
        internal static string OffsetMustBeValid {
            get {
                return ResourceManager.GetString("OffsetMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter &apos;{0}&apos; has already been defined. ähnelt.
        /// </summary>
        internal static string ParameterAlreadyDefined {
            get {
                return ResourceManager.GetString("ParameterAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter cannot have a negative value ähnelt.
        /// </summary>
        internal static string ParameterCannotBeNegative {
            get {
                return ResourceManager.GetString("ParameterCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter cannot be null ähnelt.
        /// </summary>
        internal static string ParameterCannotBeNull {
            get {
                return ResourceManager.GetString("ParameterCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter is invalid. ähnelt.
        /// </summary>
        internal static string ParameterIsInvalid {
            get {
                return ResourceManager.GetString("ParameterIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter &apos;{0}&apos; must be defined. ähnelt.
        /// </summary>
        internal static string ParameterMustBeDefined {
            get {
                return ResourceManager.GetString("ParameterMustBeDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter &apos;{0}&apos; was not found during prepare. ähnelt.
        /// </summary>
        internal static string ParameterNotFoundDuringPrepare {
            get {
                return ResourceManager.GetString("ParameterNotFoundDuringPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password must be valid and contain length characters ähnelt.
        /// </summary>
        internal static string PasswordMustHaveLegalChars {
            get {
                return ResourceManager.GetString("PasswordMustHaveLegalChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This category includes a series of counters for MySQL. ähnelt.
        /// </summary>
        internal static string PerfMonCategoryHelp {
            get {
                return ResourceManager.GetString("PerfMonCategoryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .NET Data Provider for MySQL ähnelt.
        /// </summary>
        internal static string PerfMonCategoryName {
            get {
                return ResourceManager.GetString("PerfMonCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The number of times a procedures metadata had to be queried from the server. ähnelt.
        /// </summary>
        internal static string PerfMonHardProcHelp {
            get {
                return ResourceManager.GetString("PerfMonHardProcHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hard Procedure Queries ähnelt.
        /// </summary>
        internal static string PerfMonHardProcName {
            get {
                return ResourceManager.GetString("PerfMonHardProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The number of times a procedures metadata was retrieved from the client-side cache. ähnelt.
        /// </summary>
        internal static string PerfMonSoftProcHelp {
            get {
                return ResourceManager.GetString("PerfMonSoftProcHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soft Procedure Queries ähnelt.
        /// </summary>
        internal static string PerfMonSoftProcName {
            get {
                return ResourceManager.GetString("PerfMonSoftProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die same name are not supported. ähnelt.
        /// </summary>
        internal static string ProcAndFuncSameName {
            get {
                return ResourceManager.GetString("ProcAndFuncSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Packets larger than max_allowed_packet are not allowed. ähnelt.
        /// </summary>
        internal static string QueryTooLarge {
            get {
                return ResourceManager.GetString("QueryTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reading from the stream has failed. ähnelt.
        /// </summary>
        internal static string ReadFromStreamFailed {
            get {
                return ResourceManager.GetString("ReadFromStreamFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid attempt to read a prior column using SequentialAccess ähnelt.
        /// </summary>
        internal static string ReadingPriorColumnUsingSeqAccess {
            get {
                return ResourceManager.GetString("ReadingPriorColumnUsingSeqAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Routine &apos;{0}&apos; cannot be found. Either check the spelling or make sure you have sufficient rights to execute the routine. ähnelt.
        /// </summary>
        internal static string RoutineNotFound {
            get {
                return ResourceManager.GetString("RoutineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connector/Net no longer supports server versions prior to 5.0 ähnelt.
        /// </summary>
        internal static string ServerTooOld {
            get {
                return ResourceManager.GetString("ServerTooOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Socket streams do not support seeking ähnelt.
        /// </summary>
        internal static string SocketNoSeek {
            get {
                return ResourceManager.GetString("SocketNoSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retrieving procedure metadata for {0} from procedure cache. ähnelt.
        /// </summary>
        internal static string SoftProcQuery {
            get {
                return ResourceManager.GetString("SoftProcQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stored procedures are not supported on this version of MySQL ähnelt.
        /// </summary>
        internal static string SPNotSupported {
            get {
                return ResourceManager.GetString("SPNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The stream has already been closed ähnelt.
        /// </summary>
        internal static string StreamAlreadyClosed {
            get {
                return ResourceManager.GetString("StreamAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  The stream does not support reading ähnelt.
        /// </summary>
        internal static string StreamNoRead {
            get {
                return ResourceManager.GetString("StreamNoRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The stream does not support writing ähnelt.
        /// </summary>
        internal static string StreamNoWrite {
            get {
                return ResourceManager.GetString("StreamNoWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ähnelt.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die error connecting: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached. ähnelt.
        /// </summary>
        internal static string TimeoutGettingConnection {
            get {
                return ResourceManager.GetString("TimeoutGettingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Connection Closed ähnelt.
        /// </summary>
        internal static string TraceCloseConnection {
            get {
                return ResourceManager.GetString("TraceCloseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to trace.  There are more than Int32.MaxValue connections in use. ähnelt.
        /// </summary>
        internal static string TraceErrorMoreThanMaxValueConnections {
            get {
                return ResourceManager.GetString("TraceErrorMoreThanMaxValueConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Error encountered during row fetch. Number = {1}, Message={2} ähnelt.
        /// </summary>
        internal static string TraceFetchError {
            get {
                return ResourceManager.GetString("TraceFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Connection Opened: connection string = &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string TraceOpenConnection {
            get {
                return ResourceManager.GetString("TraceOpenConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Error encountered attempting to open result: Number={1}, Message={2} ähnelt.
        /// </summary>
        internal static string TraceOpenResultError {
            get {
                return ResourceManager.GetString("TraceOpenResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Query Closed ähnelt.
        /// </summary>
        internal static string TraceQueryDone {
            get {
                return ResourceManager.GetString("TraceQueryDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Query Normalized: {2} ähnelt.
        /// </summary>
        internal static string TraceQueryNormalized {
            get {
                return ResourceManager.GetString("TraceQueryNormalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Query Opened: {2} ähnelt.
        /// </summary>
        internal static string TraceQueryOpened {
            get {
                return ResourceManager.GetString("TraceQueryOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Resultset Opened: field(s) = {1}, affected rows = {2}, inserted id = {3} ähnelt.
        /// </summary>
        internal static string TraceResult {
            get {
                return ResourceManager.GetString("TraceResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Resultset Closed. Total rows={1}, skipped rows={2}, size (bytes)={3} ähnelt.
        /// </summary>
        internal static string TraceResultClosed {
            get {
                return ResourceManager.GetString("TraceResultClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Set Database: {1} ähnelt.
        /// </summary>
        internal static string TraceSetDatabase {
            get {
                return ResourceManager.GetString("TraceSetDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Statement closed: statement id = {1} ähnelt.
        /// </summary>
        internal static string TraceStatementClosed {
            get {
                return ResourceManager.GetString("TraceStatementClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Statement executed: statement id = {1} ähnelt.
        /// </summary>
        internal static string TraceStatementExecuted {
            get {
                return ResourceManager.GetString("TraceStatementExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Statement prepared: sql=&apos;{1}&apos;, statement id={2} ähnelt.
        /// </summary>
        internal static string TraceStatementPrepared {
            get {
                return ResourceManager.GetString("TraceStatementPrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Usage Advisor Warning: Query is using a bad index ähnelt.
        /// </summary>
        internal static string TraceUAWarningBadIndex {
            get {
                return ResourceManager.GetString("TraceUAWarningBadIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Usage Advisor Warning: The field &apos;{2}&apos; was converted to the following types: {3} ähnelt.
        /// </summary>
        internal static string TraceUAWarningFieldConversion {
            get {
                return ResourceManager.GetString("TraceUAWarningFieldConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Usage Advisor Warning: Query does not use an index ähnelt.
        /// </summary>
        internal static string TraceUAWarningNoIndex {
            get {
                return ResourceManager.GetString("TraceUAWarningNoIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Usage Advisor Warning: The following columns were not accessed: {2} ähnelt.
        /// </summary>
        internal static string TraceUAWarningSkippedColumns {
            get {
                return ResourceManager.GetString("TraceUAWarningSkippedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Usage Advisor Warning: Skipped {2} rows. Consider a more focused query. ähnelt.
        /// </summary>
        internal static string TraceUAWarningSkippedRows {
            get {
                return ResourceManager.GetString("TraceUAWarningSkippedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: MySql Warning: Level={1}, Code={2}, Message={3} ähnelt.
        /// </summary>
        internal static string TraceWarning {
            get {
                return ResourceManager.GetString("TraceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to connect to any of the specified MySQL hosts. ähnelt.
        /// </summary>
        internal static string UnableToConnectToHost {
            get {
                return ResourceManager.GetString("UnableToConnectToHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to derive stored routine parameters.  The &apos;Parameters&apos; information schema table is not available and access to the stored procedure body has been disabled. ähnelt.
        /// </summary>
        internal static string UnableToDeriveParameters {
            get {
                return ResourceManager.GetString("UnableToDeriveParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to enable query analysis.  Be sure the MySql.Data.EMTrace assembly is properly located and registered. ähnelt.
        /// </summary>
        internal static string UnableToEnableQueryAnalysis {
            get {
                return ResourceManager.GetString("UnableToEnableQueryAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured attempting to enumerate the user-defined functions.  Do you have SELECT privileges on the mysql.func table? ähnelt.
        /// </summary>
        internal static string UnableToEnumerateUDF {
            get {
                return ResourceManager.GetString("UnableToEnumerateUDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to execute stored procedure &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string UnableToExecuteSP {
            get {
                return ResourceManager.GetString("UnableToExecuteSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error parsing the foreign key definition. ähnelt.
        /// </summary>
        internal static string UnableToParseFK {
            get {
                return ResourceManager.GetString("UnableToParseFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to retrieve stored routine parameters.  Either grant access to the routine or add the &apos;Use Procedure Bodies=false&apos; option to your connection string. ähnelt.
        /// </summary>
        internal static string UnableToRetrieveParameters {
            get {
                return ResourceManager.GetString("UnableToRetrieveParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to retrieve stored procedure metadata for routine &apos;{0}&apos;.  Either grant  SELECT privilege to mysql.proc for this user or use &quot;use procedure bodies=false&quot; with  your connection string. ähnelt.
        /// </summary>
        internal static string UnableToRetrieveSProcData {
            get {
                return ResourceManager.GetString("UnableToRetrieveSProcData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to start a second async operation while one is running. ähnelt.
        /// </summary>
        internal static string UnableToStartSecondAsyncOp {
            get {
                return ResourceManager.GetString("UnableToStartSecondAsyncOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unix sockets are not supported on Windows ähnelt.
        /// </summary>
        internal static string UnixSocketsNotSupported {
            get {
                return ResourceManager.GetString("UnixSocketsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The requested column value could not be treated as or conveted to a Guid. ähnelt.
        /// </summary>
        internal static string ValueNotSupportedForGuid {
            get {
                return ResourceManager.GetString("ValueNotSupportedForGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Writing to the stream failed. ähnelt.
        /// </summary>
        internal static string WriteToStreamFailed {
            get {
                return ResourceManager.GetString("WriteToStreamFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter &apos;{0}&apos; is not found but a parameter with the name &apos;{1}&apos; is found. Parameter names must include the leading parameter marker. ähnelt.
        /// </summary>
        internal static string WrongParameterName {
            get {
                return ResourceManager.GetString("WrongParameterName", resourceCulture);
            }
        }
    }
}
